name: command_line
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  p2p_chat_core:
    path: ../core
  args: ^2.1.1

dev_dependencies:
  pedantic: ^1.10.0
