name: p2p_chat_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dependencies:
  json_annotation: ^4.3.0
  meta: ^1.7.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.0.0
  # required for json code auto-generation
  json_serializable: ^6.0.1
